### PR TITLE
Remove blank lemmas from greek_lemmatized_sents

### LINKED ISSUE #3: greek_lemmatized_sents.pickle contains empty lemmata
This is from a conversation that started at https://github.com/cltk/cltk/issues/1051. I am looking at commit a68b983734d34df16fd49661f11c4ea037ab173a.

One of the elements of [`BackoffGreekLemmatizer`](https://github.com/cltk/cltk/blob/de3f4fb72ed557101538e215b0e8096ad7ccb811/cltk/lemmatize/greek/backoff.py#L16) is a [`UnigramLemmatizer`](https://github.com/cltk/cltk/blob/de3f4fb72ed557101538e215b0e8096ad7ccb811/cltk/lemmatize/backoff.py#L218) that is trained on [greek_lemmatized_sents.pickle](https://github.com/cltk/grc_models_cltk/blob/8ed2b88a89152041de27e9adf82b59fc2de465ee/lemmata/backoff/greek_lemmatized_sents.pickle). greek_lemmatized_sents.pickle contains some sentences that have a word that maps to an empty lemma (`''`), 547 sentences out of 33555 total. Some of these empty lemmata survive the [training process](https://github.com/nltk/nltk/blob/3.5/nltk/tag/sequential.py#L154) and result in `BackoffGreekLemmatizer` returning empty strings for certain words.

```
>>> import os.path, pickle
>>> with open(os.path.expanduser("~/cltk_data/greek/model/greek_models_cltk/lemmata/backoff/greek_lemmatized_sents.pickle"), "rb") as f:
...     model = pickle.load(f)
>>> len(model)
33555
>>> len([sentence for sentence in model if any(not lemma for (word, lemma) in sentence)])
547
>>> for sentence in (sentence for sentence in model if any(not lemma for (word, lemma) in sentence)): print(sentence)
[('ὑμᾶς', 'σύ'), ('δὲ', 'δέ'), ('χρὴ', 'χρή'), ('νῦν', 'νῦν'), (',', ','), ('καὶ', 'καί'), ('τὸν', 'ὁ'), ('ἐλλείποντ̓', 'ἐλλείπω'), ('ἔτι', 'ἔτι'), ('ἥβης', 'ἥβη'), ('ἀκμαίας', 'ἀκμαῖος'), ('καὶ', 'καί'), ('τὸν', 'ὁ'), ('ἔξηβον', 'ἔξηβος'), ('χρόνῳ', 'χρόνος'), (',', ','), ('βλαστημὸν', 'βλαστημός'), ('ἀλδαίνοντα', 'ἀλδαίνω'), ('σώματος', 'σῶμα'), ('πολύν', 'πολύς'), (',', ','), ('ὥραν', 'ὥρα'), ('τ̓', 'τε'), ('ἔχονθ̓', 'ἔχω'), ('ἕκαστον', 'ἕκαστος'), ('ὥστε', 'ὥστε'), ('συμπρεπές', 'συμπρεπής'), (',', ','), ('πόλει', 'πόλις'), ('τ̓', 'τε'), ('ἀρήγειν', 'ἀρήγω'), ('καὶ', 'καί'), ('θεῶν', 'θεός'), ('ἐγχωρίων', 'ἐγχώριος'), ('βωμοῖσι', 'βωμός'), (',', ','), ('τιμὰς', 'τιμή'), ('μὴ', 'μή'), ('̓', ''), ('ξαλειφθῆναί', 'ἐξαλείφω'), ('ποτε', 'ποτέ'), ('·', '·')]
[('ἔτι', 'ἔτι'), ('δὲ', 'δέ'), ('γᾶς', 'γῆ'), ('ἐμᾶς', 'ἐμός'), ('πεδί̓', 'πεδίον'), ('ὁπλόκτυπ̓', 'ὁπλόκτυπος'), ('ὠ', ''), ('-', '-'), ('τὶ', 'οὖς'), ('χρίμπτει', 'χρίμπτω'), ('βοάν', 'βοή'), ('·', '·')]
[('ὁ', 'ὁ'), ('λεύκασπις', 'λεύκασπις'), ('ὄρνυται', 'ὄρνυμι'), ('λαὸς', 'λαός'), ('εὐ', ''), ('-', '-'), ('τρεπὴς', 'εὐτρεπής'), ('ἐπὶ', 'ἐπί'), ('πόλιν', 'πόλις'), ('διώκων', 'διώκω'), ('[πόδα]', 'πούς'), ('.', '.')]
... 544 more ...
```

### PR DESCRIPTION
**Pull request by diyclassics**
Fixes #3. Blank lemmas removed from 619 token/lemma pairs (out of 549,287 pairs in 33,555 sentences).

### CODE REVIEW

**Comment by kylepjohnson** [comment]
Got it. Patrick should I expect a PR for the master repo too?

**Comment by diyclassics** [comment]
Yes, will be making additional changes to the lemmatizer code soon.

**Comment by kylepjohnson** [comment]
Perfect ping me when that PR is finished and I will merge them both!

Feb 11, 2021, 08:34 by notifications@github.com:

**Comment by diyclassics** [comment]
> Perfect ping me when that PR is finished and I will merge them both!

Should be all set both here on on the main repo.

**Comment by kylepjohnson** [comment]
Ok will get to it this week!

Apr 13, 2021, 18:30 by ***@***.***:

**Review by kylepjohnson — APPROVED** [review]

**Pull request merged**
